### ISSUE TITLE
Missing dependency issue: bluebird

### ISSUE THREAD

**Issue by SebastianMetzger** [mgreschke/node-fastbill-automatic#3]
I love the idea of a promise based API wrapper for Fastbill automatic, but there seems to be a missing dependency issue in the current version:

``` javascript
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Sebastian\snapaddy\snapaddy-payment\node_modules\node-fastbill-automatic\build\lib\utils\http.js:35:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by mgreschke** [comment]
Hi Sebastian,

Thanks a lot for reporting the issue. It should be fixed now! 
There was indeed an old bluebird import to mock Promises non-natively from back it was needed.

Regards,
Max
